### ISSUE TITLE
training label        

### ISSUE THREAD

**Issue by mensaochun** [HotaekHan/SSTDNet#3]
so nice to share the code here.
I have a question, the text bounding box may be incline in one image. so to determine a inline bounding box, (xmin, ymin, xmax, ymax) is not enough, for example, we may need three points to determine a bounding box. why here, you only use (xmin, ymin, xmax, ymax) for training labels? 
thank!

**Comment by HotaekHan** [comment]
Hello :)
First of all, thanks for visit.
Yes, you're right. if you want to predict text box, you need more parameters to handle rotation I think.
Or may I got wrong what you say because I'm not familiar with text box detection problem.
I re-implemented SSTDNet for object detection problem so I only need 4 parameters to determine bounding box.
Thanks!

**Comment by mensaochun** [comment]
Thank you for your replying!
You got right what I say. In real scene, That multi-orientation text exists in the natural image is a general thing. So In the original paper of _Single Shot Text Detector with Regional Attention_, multi-orientation text is detected. But, the author only share the test code nor training code, so I feel confused about the details.
Anyway, thank you again.

**Comment by HotaekHan** [comment]
Author may use more than 4 parameter for bounding box as my think.
I think you can check from ICDAR 2013 or 2015 dataset.

**Comment by mensaochun** [comment]
@HotaekHan
OK, I will check it later. Thanks.
