### ISSUE TITLE
Prepare dataset

### ISSUE THREAD

**Issue by xsvonjhs** [HotaekHan/SSTDNet#7]
Hi, I've downloaded a public dataset with annotation, and I've followed the instructions on README, but i'm not sure whether I can just proceed like that.
I see there is a resize function on datagen.py, does it mean I can include image with different sizes/rectangular image? Also, if there is a resize function, will the annotation be affected? Should I change it to relative value instead? 

Thanks in advance!

**Comment by HotaekHan** [comment]
Hi, thanks for visit :)
which step do you feel difficult?
yes, if you set negative value for 'num_crops' and 'input_image_size' is different with 'original_image_size', then your input image is resized. of cource it will affect to annotation boxes. And if you set positive value for 'num_crops' and 'input_image_size' is different with 'original_image_size', then your input image is cropped. please check out from 137 line to 148 line in 'datagen.py'.
i don't understand what you mean about relative value. please could you show me some example?

**Comment by xsvonjhs** [comment]
Thanks for the quick reply! 

I've read through the lines, but I am still missing some part...How about rectangular image? Should i change them to square size beforehand? 

Actually that's an advice from someone I know...to change the annotation from e.g.1344 626 1432 1237 to values 0~1, so that any resizing will not affect the annotation to much...but I wonder it can work with your code?

**Comment by HotaekHan** [comment]
no, you don't need to change to square size. this model is fully convolutional model so don't care about image size.

well..i recommend to normalize 'image value' from 0-255 to 0-1. i'm not sure about annotation box. because this model use 'anchor box' so it predict only delta value(x, y..). please check out 'encoder.py'. specifically, check from 99 line to 101 line. it show how to encode the target value for boxes.
and this code don't normalize annotation box values to 0~1.

**Comment by xsvonjhs** [comment]
I see, thanks for clearing that up!
